lib/twitter_web/router.ex
defmodule TwitterWeb.Router do
  use TwitterWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TwitterWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TwitterWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/posts", PostController, param: "post_id"

    resources "/browse/:author_id", BrowseController,
      only: [:index, :show],
      param: "post_id" do
      post "/like", BrowseController, :like, as: :like
      delete "/unlike", BrowseController, :unlike, as: :unlike
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", TwitterWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TwitterWeb.Telemetry
    end
  end
end

lib/twitter_web/controllers/browse_controller.ex
defmodule TwitterWeb.BrowseController do
  use TwitterWeb, :controller
  alias Twitter.Twits
  import Ecto.Query, warn: false

  plug :authenticate_user

  @doc """
  list all posts made by any user
  """
  @spec index(Plug.Conn.t(), map(), User.t()) :: Plug.Conn.t()
  def index(conn, %{"author_id" => author_id}, _current_user) do
    posts = Twits.list_posts_by_author_id(author_id)
    render(conn, "index.html", posts: posts)
  end

  @doc """
  show a public post /browse/author_id/post_id
  """
  @spec show(Plug.Conn.t(), map(), User.t()) :: Plug.Connt.t()
  def show(conn, %{"author_id" => author_id, "post_id" => post_id}, _current_user) do
    post = Twits.get_post!(author_id, post_id)
    render(conn, "show.html", post: post)
  end

  @doc """
  add like for a given post_id. Here, browse_post_id is the post_id
  """
  @spec like(Plug.Conn.t(), map(), User.t()) :: Plug.Conn.t()
  def like(conn, %{"author_id" => author_id, "browse_post_id" => browse_post_id}, current_user) do
    case Twits.create_like(current_user, author_id, browse_post_id) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "You liked this")
        |> redirect(to: Routes.browse_path(conn, :show, author_id, browse_post_id))

      {:error, _} ->
        conn
        |> put_flash(:info, "Couldn't send like")
        |> redirect(to: Routes.browse_path(conn, :show, author_id, browse_post_id))
    end
  end

  @doc """
  delete like for a given post
  """
  @spec unlike(Plug.Connt.t(), map(), User.t()) :: Plug.Conn.t()
  def unlike(conn, %{"author_id" => author_id, "browse_post_id" => browse_post_id}, current_user) do
    case Twits.delete_like(current_user, browse_post_id) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Like removed")
        |> redirect(to: Routes.browse_path(conn, :show, author_id, browse_post_id))

      {:error, _} ->
        conn
        |> put_flash(:info, "Couldn't delete like")
        |> redirect(to: Routes.browse_path(conn, :show, author_id, browse_post_id))
    end
  end

  def action(conn, _) do
    args = [conn, conn.params, conn.assigns.current_user]
    apply(__MODULE__, action_name(conn), args)
  end
end

lib/twitter_web/views/browse_view.ex
defmodule TwitterWeb.BrowseView do
  use TwitterWeb, :view
end

lib/twitter_web/templates/browse/index.html.eex
<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for post <- @posts do %>
    <tr>
      <td><%= post.body %></td>
      <td><%= length(post.likes) %></td>
      <td>
        <span> <%= link "Show", to: Routes.browse_path(@conn, :show, post.user_id, post.id) %></span>
        <span> <%= link "Like", to: Routes.browse_like_path(@conn, :like, post.user_id, post.id) %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

lib/twitter_web/templates/browse/show.html.eex
<h1>Show Public Post</h1>

<ul>

  <li>
  <strong>Content</strong>
    <%= @post.user.username %>
    <%= @post.body %>
  </li>
</ul>

<table>
  <thead>
    <tr>
      <th><strong>Likes:</strong></th>
      <th><%= length(@post.likes) %></th>
    </tr>
  </thead>
  <tbody>
<%= if  length(@post.likes) > 0 do %>
  <%= for like <- @post.likes do %>
      <tr>
        <td><%= like.user.username %></td>
      </tr>
  <% end %>
<% end %>
  </tbody>
</table>

<span> <%= link "Unlike", to: Routes.browse_unlike_path(@conn, :unlike, @post.user_id, @post.id) %></span>
<span><%= link "Back", to: Routes.post_path(@conn, :index) %></span>